language: node_js
node_js:
  - '4'

install:
  - npm install hexo

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -a -m "Auto update docs by Travis CI."
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

notifications:

branches:
  only:
    - hexo

cache:
  directories:
    - node_modules

env:
 global:
   - GH_REF: github.com/zhengr/rzblog.github.io.git
