language: node_js
node_js: stable

install:
  - npm install hexo

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -a -m "Auto update docs by Travis CI."
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

notifications:
  webhooks:
    urls:
      - https://open.feishu.cn/officialapp/notify/52530f3bc9e667998c59cd6bc14a654ca9cfe240e0619e8b9178644e37be6390
    on_success: always # default: always
    on_failure: always # default: always
    on_start: never # default: never
    on_cancel: always # default: always
    on_error: always # default: always

branches:
  only:
    - hexo

env:
 global:
   - GH_REF: github.com/zhengr/rzblog.github.io.git
