sudo: required
language: node_js
node_js: stable
cache: npm
branches:
  only:
  - hexo
before_install:
- npm install -g hexo-cli
install:
- npm install
script:
- hexo clean
- git config --global user.name "Ghost Yang"
- git config --global user.email "ghosttw88@hotmail.com"
- sed -i'' "s~git@github.com:GhostTW/ghosttw.github.io.git~https://${REPO_TOKEN}@github.com/GhostTW/ghosttw.github.io.git~" _config.yml
- hexo deploy
